name: 'Simili-Bot Action'
description: 'Run Simili-Bot for issue triage and duplicate detection'
inputs:
  config_path:
    description: 'Path to simili configuration file'
    required: false
    default: '.github/simili.yaml'
  github_token:
    description: 'GitHub token for API access'
    required: true
  gemini_api_key:
    description: 'Google Gemini API key'
    required: true
  qdrant_url:
    description: 'Qdrant database URL'
    required: true
  qdrant_api_key:
    description: 'Qdrant API key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Post Simili-Bot Comment
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GEMINI_API_KEY: ${{ inputs.gemini_api_key }}
        QDRANT_URL: ${{ inputs.qdrant_url }}
        QDRANT_API_KEY: ${{ inputs.qdrant_api_key }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        REPO: ${{ github.repository }}
      run: |
        # Create a comment indicating Simili-Bot is configured
        COMMENT="## 🤖 Simili-Bot

Simili-Bot is active and will find similar issues using AI-powered semantic search.

**Setup Status:**
✅ Central configuration: \`similigh/simili-shared-config\`
✅ Vector database: Qdrant (\`event-int-index\` collection)
✅ Embedding provider: Google Gemini
✅ Cross-repo search: Enabled
✅ Issues indexed: $(curl -s -H \"api-key: $QDRANT_API_KEY\" \"$QDRANT_URL/collections/event-int-index\" 2>/dev/null | grep -o '\"points_count\":[0-9]*' | cut -d: -f2 || echo 'N/A') issues

When issues are indexed to Qdrant, similar issues will be detected automatically and linked here.

**Workflow:** \`issue-triage\` (similarity search + duplicate detection)
**Collection:** \`event-int-index\`
**Repository:** \`$REPO\`
**Issue:** #\`$ISSUE_NUMBER\`"

        # Post the comment
        curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/$REPO/issues/$ISSUE_NUMBER/comments" \
          -d "{\"body\": $(echo "$COMMENT" | jq -Rs .)}"
