name: 'Simili-Bot Action'
description: 'Run Simili-Bot for issue triage and duplicate detection'
inputs:
  config_path:
    description: 'Path to simili configuration file'
    required: false
    default: '.github/simili.yaml'
  github_token:
    description: 'GitHub token for API access'
    required: true
  gemini_api_key:
    description: 'Google Gemini API key'
    required: true
  qdrant_url:
    description: 'Qdrant database URL'
    required: true
  qdrant_api_key:
    description: 'Qdrant API key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Download and Extract Simili-Bot Binary
      shell: bash
      run: |
        mkdir -p /tmp/simili-bin
        cd /tmp/simili-bin

        # Detect OS and architecture
        OS=$(uname -s | tr '[:upper:]' '[:lower:]')
        ARCH=$(uname -m)

        # Map architecture names
        case $ARCH in
          x86_64)
            ARCH="amd64"
            ;;
          aarch64)
            ARCH="arm64"
            ;;
        esac

        echo "Downloading simili-bot for ${OS}-${ARCH}..."

        # Download and extract release tarball
        curl -L https://github.com/similigh/simili-bot/releases/download/v0.0.2/simili-bot_0.0.2_${OS}_${ARCH}.tar.gz -o simili-bot.tar.gz

        if [ ! -f simili-bot.tar.gz ]; then
          echo "ERROR: Failed to download binary"
          exit 1
        fi

        tar -xzf simili-bot.tar.gz

        # Find the binary (it might be in a subdirectory)
        if [ -f simili ]; then
          mv simili simili-cli
        elif [ -f simili-bot ]; then
          mv simili-bot simili-cli
        else
          echo "ERROR: Could not find binary in tarball"
          echo "Contents:"
          find . -type f
          exit 1
        fi

        chmod +x simili-cli
        echo "Binary extracted successfully"
        ./simili-cli --version || echo "Binary ready"

    - name: Create issue JSON
      shell: bash
      run: |
        mkdir -p /tmp/simili
        cat > /tmp/simili/issue.json << 'EOF'
        ${{ toJson(github.event.issue) }}
        EOF

    - name: Run Simili-Bot Process
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GEMINI_API_KEY: ${{ inputs.gemini_api_key }}
        QDRANT_URL: ${{ inputs.qdrant_url }}
        QDRANT_API_KEY: ${{ inputs.qdrant_api_key }}
        CI: 'true'
        GITHUB_ACTIONS: 'true'
      run: |
        # Run simili-bot process command with issue data in non-interactive mode
        # CI=true environment variable tells simili-bot to skip the interactive TUI
        timeout 120 /tmp/simili-bin/simili-cli process \
          --config "${{ inputs.config_path }}" \
          --issue /tmp/simili/issue.json \
          --workflow issue-triage \
          -v || true
