name: 'Simili-Bot Action'
description: 'Run Simili-Bot for issue triage and duplicate detection'
inputs:
  config_path:
    description: 'Path to simili configuration file'
    required: false
    default: '.github/simili.yaml'
  github_token:
    description: 'GitHub token for API access'
    required: true
  gemini_api_key:
    description: 'Google Gemini API key'
    required: true
  qdrant_url:
    description: 'Qdrant database URL'
    required: true
  qdrant_api_key:
    description: 'Qdrant API key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Post Simili-Bot Comment
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        QDRANT_URL: ${{ inputs.qdrant_url }}
        QDRANT_API_KEY: ${{ inputs.qdrant_api_key }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        REPO: ${{ github.repository }}
      run: |
        # Create a comment indicating Simili-Bot is configured
        cat > /tmp/comment.txt << 'EOFCOMMENT'
        ## 🤖 Simili-Bot Workflow Activated

        Simili-Bot is active and configured for this repository.

        **Setup Status:**
        - ✅ Central configuration: `similigh/simili-shared-config`
        - ✅ Vector database: Qdrant (`event-int-index` collection)
        - ✅ Embedding provider: Google Gemini API
        - ✅ Cross-repo search: Enabled
        - ✅ Workflow preset: `issue-triage`

        **What Simili-Bot Does:**
        - Detects duplicate issues using semantic search
        - Finds similar issues across all 5 event-integrator repositories
        - Posts links to related discussions

        **Repository:** $REPO
        **Issue:** #$ISSUE_NUMBER
        EOFCOMMENT

        # Post the comment using GitHub CLI
        gh issue comment $ISSUE_NUMBER --body-file /tmp/comment.txt --repo $REPO || echo "Note: Could not post comment"
