name: 'Simili-Bot Action'
description: 'Run Simili-Bot for issue triage and duplicate detection'
inputs:
  config_path:
    description: 'Path to simili configuration file'
    required: false
    default: '.github/simili.yaml'
  github_token:
    description: 'GitHub token for API access'
    required: true
  gemini_api_key:
    description: 'Google Gemini API key'
    required: true
  qdrant_url:
    description: 'Qdrant database URL'
    required: true
  qdrant_api_key:
    description: 'Qdrant API key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout simili-bot
      uses: actions/checkout@v4
      with:
        repository: similigh/simili-bot
        path: simili-bot-repo

    - name: Set up Go with caching
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true
        cache-dependency-path: simili-bot-repo/go.sum

    - name: Build simili-bot
      shell: bash
      run: |
        cd simili-bot-repo
        go build -o simili-cli ./cmd/simili

    - name: Create issue JSON
      shell: bash
      run: |
        mkdir -p /tmp/simili
        cat > /tmp/simili/issue.json << 'EOF'
        ${{ toJson(github.event.issue) }}
        EOF

    - name: Run Simili-Bot Process
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GEMINI_API_KEY: ${{ inputs.gemini_api_key }}
        QDRANT_URL: ${{ inputs.qdrant_url }}
        QDRANT_API_KEY: ${{ inputs.qdrant_api_key }}
        CI: 'true'
        GITHUB_ACTIONS: 'true'
      run: |
        cd simili-bot-repo
        # Run simili-bot process command with issue data in non-interactive mode
        # CI=true environment variable tells simili-bot to skip the interactive TUI
        timeout 180 ./simili-cli process \
          --config "${{ inputs.config_path }}" \
          --issue /tmp/simili/issue.json \
          --workflow issue-triage \
          -v || true
